targets:
  freezed_only:
    auto_apply_builders: false
    builders:
      freezed:
        enabled: true
  $default:
    dependencies: [":freezed_only"]
    builders:
      freezed:
        enabled: false
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true